services:
  - type: web
    name: poker-sim-api
    runtime: docker
    repo: https://github.com/kinyha/poker-sim
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/game/health
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://poker-sim.onrender.com
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx256m
